=== starread0000-glitch/sui/squad.dtd
<!ELEMENT squad (name, email, web, picture, title, member*)>
<!ATTLIST squad
    nick CDATA #REQUIRED
>

<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT picture (#PCDATA)>
<!ELEMENT title (#PCDATA)>

<!ELEMENT member (name, email, icq, remark)>
<!ATTLIST member
    id CDATA #REQUIRED
    nick CDATA #REQUIRED
>

<!ELEMENT icq (#PCDATA)>
<!ELEMENT remark (#PCDATA)>

=== starread0000-glitch/sui/squad.xml
<?xml version="1.0"?>
<!DOCTYPE squad SYSTEM "squad.dtd">

<squad nick="sui">
    <name>storrr</name>
    <email>N/A</email>
    <web>N/A</web>
    <picture>logo.paa</picture>
    <title>storrr</title>

    <member id="76561199230095934" nick="Ten_P">
        <name>Ten_P</name>
        <email>N/A</email>
        <icq>N/A</icq>
        <remark>Member</remark>
    </member>
</squad>
